name: CI # Continuous Integration Workflow
on: [push] # Trigger on push events
jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    steps:
    - uses: actions/checkout@v2 # Check out the repository
    - name: Set up Python # Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'
    - name: Install dependencies` # Install required Python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests # Run the test suite
      run: python -m unittest discover tests